### ISSUE TITLE
OWASP TOP 10 Refactor

### ISSUE THREAD

**Issue by UlisesGascon** [guidesmiths/cybersecurity-handbook#22]
### TODO:
- [ ] Review tools
- [ ] Add new tools referenced in other sections
- [ ] Add nodejs examples
- [ ] Add videos
- [ ] Improve and curate content
