### ISSUE TITLE
Pending things

### ISSUE THREAD

**Issue by UlisesGascon** [guidesmiths/cybersecurity-handbook#6]
### Todo 

- [x] Add licence file
- [x] Add CoC
- [x] Add Contributing.md
- [ ] Add CI for deploy and URL

### Fix

- [ ] Support emojis in .mdx files
